### PR TITLE
Set master as default branch in pipe config

### PR DESCRIPTION
**Pull request by Remusss**
By default github creates a master branch in a new repo

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by nabuskey — COMMENTED** [review]
GitHub prefers the default branch name to be `main` so I I don't think this is needed.

**Comment by Remusss** [comment]
I'm a little confused by this. The new repository I created used master as branch name by default. So unless we set this by hand I am not sure how that main branch would work in the guide
I created a new repo to recheck this
image

**Comment by nabuskey** [comment]
So there are two things here I think: 
1. When you create a git repo using `git init`. it creates a repository and sets the default branch to be w/e you have configured in your local config file. See here: https://github.blog/2020-07-27-highlights-from-git-2-28/
2. When you create a git repo using GitHub GUI or API, it defaults to main: https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

In your case, it seems you are creating a repository using `git init` and falls under point 1. Since GitHub defaults to `main`. I think the config in this repository is correct.

**Comment by Remusss** [comment]
Thanks for the info. Now it clicks. I did use the GUI to create a new repo, but I cloned it locally since it hadn't any branches and used git status to check the branch.
And yes the empty repo instructions from github mentions the main branch.

I'll close this as it's no longer relevant.

**Pull request closed without merging**
